### ISSUE TITLE
Plug-in for Hearthstone Deck Tracker?

### ISSUE THREAD

**Issue by Ansem93** [mlntn/pack-o-bot#16]
Hi! Any hope to see this program became a simple plug-in for Hearthstone Deck Tracker? I think that it would be a lot better to have it inside HTD instead as a stand alone program

**Comment by MikeFoden** [comment]
Hearthstone Deck Tracker for Windows is written in C# where as this is written in Javascript, so two different technologies.

It would need to be ported over.

**Comment by mlntn** [comment]
@MikeFoden is correct.
