### ISSUE TITLE
Only allow a single instance of the bot to run

### ISSUE THREAD

**Issue by jmxd** [mlntn/pack-o-bot#17]
I ran into an issue where i (thought i) closed the app and reopened it. Turns out the previous one was only minimized to the tray and i now had two instances of the app running at the same time, which resulted in all my packs being uploaded to pitytracker twice.

This was mostly my fault but perhaps only allow a single instance to run to prevent it from happening to others?

**Comment by davidschwegler** [comment]
This has been my top annoyance with the app over the years of using it.

**Comment by Ekkstein** [comment]
I yesterday saw this issue and took care of it. Version 0.3.3 takes care to only permit a single instance. If you have on open in the background, it will be activated and the newly opened is quit.
Thank you for the report.

**Comment by davidschwegler** [comment]
10/10 thanks!
