### ISSUE TITLE
Doesn't detect Classic Packs?

### ISSUE THREAD

**Issue by bren007pie** [mlntn/pack-o-bot#18]
Hey there's a bug where it currently doesn't detect classic packs, detects all other standard packs for me as of right now (June 9, 2018), those being: WW, Kobolds, Frozen, Ungoro. Thanks!

**Comment by Ekkstein** [comment]
I just checked and it seems to be working fine for me.

**Comment by Ekkstein** [comment]
Ok, I belief I found the problem. Strangely there was a card missing in the database. It should work again now.

**Comment by bren007pie** [comment]
Awesome, not sure if it's working as I stopped playing but thank you for the fix!

**Comment by Ekkstein** [comment]
I'll assume it works now and close this issue. Thanks for the answer.
