### ISSUE TITLE
Retrying pack upload...(statusCode: 404)

### ISSUE THREAD

**Issue by simjunjie** [mlntn/pack-o-bot#19]
My packs are not uploading. I seem to get an error "Retrying pack upload...(statusCode: 404)"

![pack-o-bot error](https://user-images.githubusercontent.com/33338446/48954021-c5e97b00-ef82-11e8-925f-84cf4177e19e.png)

**Comment by Ekkstein** [comment]
Hello sim-junjie,
could you try again and let me know if it works now?

**Comment by uberfunk** [comment]
I've had this issue since the end of October. So I entered all my pack info manually to the pitytracker website instead. Tried the upload again today and still getting the 404 error. I'm on Mac.

**Comment by simjunjie** [comment]
> Hello sim-junjie,
> could you try again and let me know if it works now?

Hello Ekkstein, the error still persists.

**Comment by clickety** [comment]
This issue is also persisting for me - also on Mac OS X.

**Comment by Ekkstein** [comment]
I think i got it. Can you check once again? If it still doesn't work, please let me know what computer you are using and then I'll have to ask you a few questions. Thank you.

**Comment by clickety** [comment]
Seems like you've got it - both my macs are caught up and functioning correctly now.

**Comment by simjunjie** [comment]
Yeah it working all right now. Thank you so much, especially since its so close to the Rastakhan release.

**Comment by uberfunk** [comment]
I can also confirmed it is now working! Just in time, thanks!

**Comment by Ekkstein** [comment]
Im glad to hear it's working now. Sorry for the delay, this is just a private side project for me. 
And just a reminder, give packobot a second or two after you open a pack, i have noticed that opening them too quickly can cause issues.
Have fun opening your packs!
