### ISSUE TITLE
Tool doesn't work

### ISSUE THREAD

**Issue by djdookie** [mlntn/pack-o-bot#2]
Hi guys,

I downloaded the tool, entered the pity tracker token and started Hearthstone.
I opened two packs, but the tool still only says "Watching for packs..." but not uploading any results.
It doesn't recognize any pack openings.
HS is at C:\Games\Hearthstone\ under Windows 10 x64.

I had to allow the tool in smartscreen, but the firewall didn't aks. Could this be an issue?
Another idea: my environment is German, but I play HS in English.

Is there a log I can inspect?

**Comment by djdookie** [comment]
I guess, the reason is, I didn't install HS on it's default path.
I saw this hardcoded in your sourcecode: "C:\\Program Files (x86)\\Hearthstone\\Logs\\"

**Comment by djdookie** [comment]
Ok I tested my theory and moved HS to C:\Program Files (x86)\Hearthstone
Now its working fine!
You should really put the HS path into a settings file. ;)
I'd like to move it back in my games folder.
And you could test for the path and warn the user, if the expected path/file is not found.

Thanks for your tool though, it saves me a lot of time!

**Comment by Ekkstein** [comment]
Thank you for the feedback. You identified the problem correctly. It's on our list of things to improve. I'm glad you got it to work.

**Comment by nikil** [comment]
Can you reopen this as a feature request, so users can track when you've implemented setting the Hearthstone path in the pack-o-bot settings?  Thanks for the great tool by the way.

**Comment by mlntn** [comment]
@nikil We have a pull request already, just haven't had a chance to test it fully. #5

**Comment by nikil** [comment]
Great - thanks!
