### ISSUE TITLE
Retrying pack upload....(statusCode: 400)

### ISSUE THREAD

**Issue by StarzeeBEAST** [mlntn/pack-o-bot#21]
I opened a RoS pack and now I'm getting this error everytime i open pack-o-bot. I'm unable to upload any packs

**Comment by Ekkstein** [comment]
Hey StarzeeBEAST,
it appears to me, that something isn't working with your token. I would like to ask you to regenerate your token and try it again. To do that, just visit: https://pitytracker.com/packobot and click regenerate and copy your new token. Then open Pack-o-Bot and paste the new token, and then save it. 
Shut down and reopen Pack-o-Bot just in case. Let me know if this still fails after.
Thank you!

**Comment by StarzeeBEAST** [comment]
Thanks for the response, you are indeed correct and it's all sorted now. Many thanks 👍

**Comment by Ekkstein** [comment]
Glad I could help. Have fun!
