### ISSUE TITLE
Near "Year of the Dragon" packs not being uploaded

### ISSUE THREAD

**Issue by Kopert** [mlntn/pack-o-bot#29]
Blizzard is selling a new bundle called "Year of the Dragon Bundle". It includes 15 "Year of the Dragon Packs" which are a new type of pack that includes card from all three card sets for 2019.

When opening these packs, this message shows up on pack-o-bot:

>This pack can't be uploaded. It's set_type is not identifyable. You can find it in packobots app directory in user.json for review.

user.json does indeed include all the packs with pending uploads.

**Comment by Ekkstein** [comment]
Hey @Kopert 
Year of the Dragon Packs are not supported by Pitytracker, because they contain cards of multiple sets, which is not aligned with our data structure. We decided to not support those packs.
Packobot has been updated to keep those packs in a user.json file for your review.
