### ISSUE TITLE
Retrying pack upload...(400)

### ISSUE THREAD

**Issue by interro-bang** [mlntn/pack-o-bot#6]
Uploaded first pack successfully, second pack loops through "retrying" and can't upload

**Comment by mlntn** [comment]
Was this related to #7? If not and this pack has not sent, can you please paste the contents of %USERPROFILE%\AppData\Roaming\pack-o-bot\packs.json so we can debug the issue?

**Comment by interro-bang** [comment]
Yeah assume this could have been because of multiple processes, and packs.json is cleared already

**Comment by mlntn** [comment]
Okay, thanks! I'll add a single-process check to the list.
