### ISSUE TITLE
JavaScript error on launch

### ISSUE THREAD

**Issue by interro-bang** [mlntn/pack-o-bot#7]
Error on almost every launch

![image](https://user-images.githubusercontent.com/19805843/29334361-0ca779ea-81ff-11e7-9fb1-6cc7c6a84c63.png)

**Comment by interro-bang** [comment]
Error while running, after uploading two packs successfully.
After those three errors appeared again and all dismissed, that pack also uploaded ok
![image](https://user-images.githubusercontent.com/19805843/29334660-19d3fade-8200-11e7-90d3-abef79cad868.png)

Next pack threw errors and failed

Edit: Found this was due to more than one group of pack-o-bot.exe processes running (had closed previous window but not from system tray, relaunching didn't warn that it was running already)

**Comment by Ekkstein** [comment]
Multiple App instances are now prevented (as of 0.3.3) I assume this would prevent this issue.
