### ISSUE TITLE
pack o bot uploads duplicate packs

### ISSUE THREAD

**Issue by danktanks** [mlntn/pack-o-bot#8]
My pack o bot finds a pack and uploads many records of it

**Comment by mlntn** [comment]
Can you please provide the following:
1. Platform: PC or Mac?
2. Your Achievements.log file with a pack in it that was sent multiple times by pack-o-bot.
3. Your cards.json file in your pack-o-bot user settings. 

Thanks!

**Comment by danktanks** [comment]
Im on windows, I do not know how to locate the files you need

**Comment by mlntn** [comment]
Thanks! Here are the file locations:
2. C:\Program Files (x86)\Hearthstone\Logs\Achievements.log
3. %USERPROFILE%\AppData\Roaming\pack-o-bot\packs.json

**Comment by danktanks** [comment]
[New folder.zip.zip](https://github.com/mlntn/pack-o-bot/files/1234936/New.folder.zip.zip)

[Uploading New folder.zip…]()

**Comment by mlntn** [comment]
There are no packs in either of those files. Are you still seeing the pack upload multiple times?

**Comment by danktanks** [comment]
im about to open 40 i can let you know

**Comment by mlntn** [comment]
Maybe open the first 1 or 2 and make sure that it's uploading them to pitytracker.com.

**Comment by danktanks** [comment]
The issue was that multiple folders of Pack-o-bot were downloaded, even though only one application was open and running, it seems that each folder was creating a record in pity tracker. after deleting all folders but 1, it now uploads only 1 pack

**Comment by mlntn** [comment]
It's possible multiple applications were running. We have a ticket open to fix that. Thanks for reporting this, glad you were able to get it working.
